### ISSUE TITLE
OPAM package?

### ISSUE THREAD

**Issue by camlspotter** [ocaml-doc/octavius#1]
Hi Leo,

Is it possible to publish octavius in the official OPAM repo?

**Comment by lpw25** [comment]
I haven't made an initial release yet -- and I hope to make significant changes before I do -- so I wasn't going to publish it on OPAM anytime soon.

Is there any particular reason you would like it to be published now?

**Comment by camlspotter** [comment]
Thanks for the reply.

I want to implement doctest, tests embeded in documents like https://github.com/sol/doctest#readme . OCamlDoc comments are now accessible as `[@ocaml.doc]` attribute in Parsetree, and what is now missing is the extraction of the code part.

I checked OCamlDoc's lexer+parser first but it is not easy to use: the code is obtained in Yacc level and it lacks the position information.  In Octavius, the code part is already available at the lexer level and its location is easily obtainable. So, in short, what I want to use essentially in Octavius is `OctLexer` (and of course `OctTypes`).

**Comment by dbuenzli** [comment]
This will happen at some point in the near future.
