### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by XVilka** [ocaml-doc/octavius#10]
With dune 2.0 integration Octavius blocks dune upgrade by depending on jbuilder.transition. I see that it was upgraded in the master, but wasn't released in opam.

**Comment by aantron** [comment]
Thanks for reporting. I'll take a look and make a release.

**Comment by kit-ty-kate** [comment]
Just in case it helps to have a direct link to what has changed since the last release: https://github.com/ocaml-doc/octavius/compare/v1.2.1..master

**Comment by aantron** [comment]
I created a [release](https://github.com/ocaml-doc/octavius/releases/tag/v1.2.2). Closing this in favor of https://github.com/ocaml/opam-repository/pull/15418. Thanks again.
