### ISSUE TITLE
Support for 4.02

### ISSUE THREAD

**Issue by trefis** [ocaml-doc/octavius#5]
Every other dependency of odoc still works with 4.02 AFAIK, it is a bit sad that octavius doesn't.
It seems easy enough to add back support, which I think we should do before "the release".

**Comment by dbuenzli** [comment]
I'm not sure this is a great idea IIRC the 4.02 line was consistently broken w.r.t. to cmti gen (the duplication stuff) we are only going to get reports about broken docs.

**Comment by dbuenzli** [comment]
Are we ok in labelling `wontfix` and closing this ?

**Comment by trefis** [comment]
Yes.
