### ISSUE TITLE
4.08 support

### ISSUE THREAD

**Issue by copy** [ocaml-doc/octavius#8]
On 4.08.0+beta1:

```
File "test/main.ml", line 25, characters 14-26:
25 |     Location.(report_error Format.err_formatter (error ~loc msg));
                   ^^^^^^^^^^^^
Error: Unbound value report_error
```

**Comment by aantron** [comment]
@copy Octavius has been replaced by a [different parser](https://github.com/ocaml/odoc/blob/126063d3c4e423ab488354c28b841a44e4d5dbdd/src/parser/odoc__parser.mli) in odoc. Octavius is not properly deprecated, because, IIRC, it is used in `ppx_js_style`. However, development may be slow.

**Comment by dbuenzli** [comment]
OT

@aantron except apparently for `octavius` wouldn't it make sense to GitHub archive the other repos ? (e.g. the issues I filed in these repos appear in my global issue list but I guess they will never be closed).

**Comment by aantron** [comment]
I'm for archiving them. Last we discussed this (https://github.com/ocaml-doc/doc-ock-html/issues/11#issuecomment-436440127 IIRC), I wasn't sure if maybe @lpw25, @trefis, or others have branches written against them. @lpw25, @trefis, would you comment?

My overall impression is that we work only in the odoc repo now, but I'd like to confirm.

**Comment by dbuenzli** [comment]
> Last we discussed this ([ocaml-doc/doc-ock-html#11 (comment)](https://github.com/ocaml-doc/doc-ock-html/issues/11#issuecomment-436440127) IIRC),

Yikes, I'm forgetful.

**Comment by trefis** [comment]
I can't speak for the other repos (@lpw25 has some branches, but I don't know if it's against the new or old repos), but octavius has other users than odoc (at least ppx_js_style and ocamlformat, maybe others).

**Comment by copy** [comment]
Fixed in https://github.com/ocaml-doc/octavius/commit/bc1c0539b35d2bb4812ce4ff12c637157efe5f28
